### ISSUE TITLE
Add locking

### ISSUE THREAD

**Issue by Gottox** [Qabel/ackack#5]
Ackack should support a way of locking objects while they are changed by an Actor.

**Comment by thechauffeur** [comment]
What is this?

**Comment by thechauffeur** [comment]
@L-Henke do what you want with this. You can close it, too.

**Comment by L-Henke** [comment]
@thechauffeur and I think, that it is pretty unlikely that a resource is changed by two modules at the same time. Instead of locking, it might be more useful for us to have something like a last written timestamp in the resources and let the resource actors check if a write would overwrite changes from somewhere else and return an error in that case.
